name: first-workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      id: checkout
      uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: make setup
      - run: make test
      - run: make lint
      - name: Print Hello from Hexlet
      uses: hexlet-components/hello-from-hexlet-action@release
